name: Python Lint For Matrix

on: 
  push:
    branches: [main]

jobs:
  Validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    
    
      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: pip install -r requirements.txt
      
      - name: Run Linter
        run: flake8 app.py
